Explorate/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for,session
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        Username = request.form.get('Username')
        password3 = request.form.get('password3')

        user = User.query.filter_by(Username=Username).first()
        if user:
            if check_password_hash(user.password, password3):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                print("User logged in:", user.Username)
                return redirect(url_for('main.FindAdv'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist.', category='error')
    
    return render_template("auth.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    # session.pop('user_id', None)
    session.clear()
    logout_user()
    return redirect(url_for('main.home'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        Username = request.form.get('createUsername')
        password1 = request.form.get('password')
        password2 = request.form.get('confirmPassword')
        birthdate = request.form.get('birthdate')
        country = request.form.get('country')

        if not all([email, Username, password1, password2, birthdate, country]):
            flash('Please fill out all fields.', category='error')
            return redirect(url_for('auth.sign_up', form='signup'))
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
            return redirect(url_for('auth.sign_up', form='signup'))
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
            return redirect(url_for('auth.sign_up', form='signup'))
        elif len(Username) < 2:
            flash('Username must be greater than 1 character.', category='error')
            return redirect(url_for('auth.sign_up', form='signup'))
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
            return redirect(url_for('auth.sign_up', form='signup'))
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
            return redirect(url_for('auth.sign_up', form='signup'))
        else:
            new_user = User(Username=Username,email=email,  password=generate_password_hash(password1, method='pbkdf2:sha256'),dateofbirth=birthdate, country=country)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))

    return render_template("auth.html", user=current_user)

Explorate/routes.py
from flask import Blueprint, render_template, request, jsonify, url_for, session
from collections import Counter
from sqlalchemy.sql import tuple_

#from app import db
from Explorate.models import db,Adventure, UserSelection, User, Recommendations, Ratings, UserFriend
import random
from flask_login import current_user, login_required, logout_user
import uuid


# Define the Blueprint
main = Blueprint('main', __name__)

@main.route('/')
def home():
    # Render a Jinja template
    if current_user.is_authenticated:
        return render_template('Data_Entry.html') 
    return render_template('base.html', show_nav=True)

@main.route('/auth')
def auth():
    return render_template('auth.html')

# Define routes using the Blueprint
@main.route('/FindAdv')
@login_required
def FindAdv():
    return render_template('Data_Entry.html')  # Replace 'index.html' with your main HTML file name


@main.route('/adventure')
@login_required
def adventure():
    return render_template('Adv_name.html')  # Assumes the file is in the `templates/` directory


@main.route('/index')
@login_required
def index():
    return render_template('index.html')  # Assumes the file is in the `templates/` directory




@main.route('/questions', methods=['POST', 'GET'])
@login_required
def questions():
    csrf_token = request.headers.get('X-CSRF-Token')
    # try:
    #     validate_csrf(csrf_token)
    # except Exception as e:
    #     return jsonify({'error': 'CSRF validation failed'}), 400
    if request.method == 'POST':
        # Parse JSON data from the request
        data = request.get_json()
        adventure_name = data.get('adventure_name', 'Adventure1')
        adults = data.get('adults', 0)
        children = data.get('children', 0)
        pets = data.get('pets', 0)
        choice = data.get('choice', 'No')

        # Use the currently logged-in user's ID
        user_id = current_user.id
        Username= current_user.Username
        print(f"Current user ID: {user_id}")
        session['user_id'] = user_id
        session['Username'] = Username

        # Save data to the Adventure table
        new_trip = Adventure(
            adventure_name=adventure_name,
            adults=adults,
            children=children,
            pets=pets,
            choice=choice,
            user_id=user_id,
        )
        db.session.add(new_trip)
        db.session.commit()

        # Get the generated adventure_id from the newly added adventure
        adventure_id = new_trip.id
        user_id = new_trip.user_id

        # Log the operation
        print(f"Adventure saved with ID: {adventure_id}")
        print(f"Adventure saved with ID: {user_id}")

        # Render the next page dynamically
        return render_template(
            'Data_Ent_Q1.html',
            adventure_name=adventure_name,
            adults=adults,
            children=children,
            pets=pets,
            choice=choice,
            adventure_id=adventure_id,  # Pass the adventure_id to the template for later use
            user_id=user_id 
        )
    
    # Handle GET request
    return render_template('Data_Ent_Q1.html', adventure_name="Adventure1")




# Share page routes
@main.route('/share_page')
@login_required
def share_page():
    return render_template('share-page.html')

@main.route('/share_blog')
@login_required
def share_blog():
    return render_template('share-blog.html')

@main.route('/rate_page')
@login_required
def rate_page():
    return render_template('rate-page.html')

# new route to handle submission of ratings
@main.route('/submit_rating', methods=['POST'])
@login_required
def submit_rating():
    data = request.get_json()
    print("Received payload:", data)
    if not data:
        return jsonify({'error': 'No JSON data received'}), 400

    #user_id = data['user_id']
    #adventure_id = data['adventure_id']
    recommendation_id = session.get('recommendation_id')
    if not recommendation_id:
        return jsonify({'error': 'Recommendation ID is required.'}), 400

    location_rating = data.get('location_rating', 0)
    food_rating = data.get('food_rating', 0)
    attractions_rating = data.get('attractions_rating', 0)
    accommodation_rating = data.get('accommodation_rating', 0)
    overall_rating = data.get('overall_rating', 0)
    
    # add logic to store data in database
    rating = Ratings(
        #user_id=user_id,
        #adventure_id=adventure_id,
        recommendation_id = recommendation_id,
        location_rating=location_rating,
        food_rating=food_rating,
        attractions_rating=attractions_rating,
        accommodation_rating=accommodation_rating,
        overall_rating=overall_rating
    )
    print("Rating object created:", rating)
    db.session.add(rating)
    db.session.commit()
    
    return jsonify({'message': 'Rating submitted successfully'}),200

@main.route('/other_trips')
@login_required
def other_trips():
    return render_template('other-trips.html')


# Processing logic for recommendations


@main.route('/save_selections', methods=['POST'])
@login_required
def save_selections():
    try:
        data = request.json
        print("Received payload:", data)

        selections = data.get('selections', [])
        adventure_id = data.get('adventure_id')
        user_id = data.get('user_id')
        print(f"Userrrrr ID: {user_id}")
        

        if not selections or len(selections) < 5:
            return jsonify({"error": "At least 5 inputs are required."}), 400

        if not adventure_id:
            return jsonify({"error": "Adventure ID is required."}), 400

        # Validate adventure existence
        adventure = Adventure.query.get(adventure_id)
        if not adventure:
            return jsonify({'message': 'Adventure not found'}), 404

        # Save user selections
        session_id = str(uuid.uuid4())
        selection = UserSelection(
            session_id=session_id,
            answer_1=selections[0],
            answer_2=selections[1],
            answer_3=selections[2],
            answer_4=selections[3],
            answer_5=selections[4],
            adventure_id=adventure_id
        )
        session['user_id'] = user_id
        print(f"User ID: {user_id}")
        db.session.add(selection)
        db.session.commit()  # Save user selections first
        print("User selection saved successfully.")

        # Recommendation processing
        state_mappings = {
        "Hot": ["South Australia", "Western Australia", "Northern Territory"],
        "Cold": ["Tasmania", "Victoria"],
        "Tropical": ["Queensland", "New South Wales", "Northern Territory"],
        "Beaches": ["New South Wales", "Queensland", "Western Australia", "South Australia"],
        "Nature": ["New South Wales", "Queensland", "Tasmania", "Western Australia", "Victoria", "Northern Territory"],
        "Outback": ["South Australia", "Western Australia", "Northern Territory"],
        "Adventure": ["New South Wales", "Queensland", "Western Australia", "Tasmania", "Northern Territory"],
        "Sport": ["Victoria", "New South Wales", "Tasmania"],
        "Family-friendly": ["Queensland", "New South Wales", "Northern Territory"],
        "Cultural/Arts": ["New South Wales", "Victoria", "South Australia", "Tasmania", "Northern Territory"],
        "Heritage/History": ["Tasmania", "Victoria", "South Australia", "Northern Territory"],
        "Landmarks": ["Queensland", "New South Wales", "Northern Territory", "Western Australia"],
        "Coastal / Scenic Drives": ["Queensland", "Victoria", "Tasmania", "South Australia", "Northern Territory"],
        "Mountain": ["New South Wales", "Victoria", "Tasmania", "Northern Territory"],
        "Wildlife": ["Queensland", "South Australia", "Tasmania", "Western Australia", "Northern Territory"],
        "Food and Wine": ["New South Wales", "Victoria", "South Australia", "Western Australia"]
        }
    
        location_data = {
        "Tasmania": {
            "Family-Friendly": ["Bonorong Wildlife Sanctuary", "Tasmanian Museum and Art Gallery", "Launceston City Park", "ZooDoo Wildlife Park"],
            "Sport": ["Blundstone Arena", "Silverdome Launceston"],
            "Adventure": ["Cradle Mountain-Lake St Clair", "Three Capes Track", "Gordon River Cruises", "Hastings Caves"],
            "Cultural/Arts": ["MONA", "Salamanca Arts Centre", "Theatre Royal", "TMAG"],
            "Beaches": ["Wineglass Bay", "Bay of Fires", "Seven Mile Beach", "Boat Harbour Beach", "Adventure Bay"],
            "Nature": ["Mount Field National Park", "Tarkine Wilderness", "The Nut", "Southwest National Park", "Derwent Valley"],
            "Food and Wine": ["Tamar Valley", "Bruny Island Cheese", "Hobart Salamanca Market", "Huon Valley"],
            "Coastal/Scenic Drives": ["Great Eastern Drive", "Huon Trail", "West Coast Wilderness Drive"],
            "Mountain": ["Cradle Mountain", "Mount Wellington", "Frenchmans Cap", "Hartz Mountains"],
            "Wildlife": ["Maria Island", "Bonorong Sanctuary", "Narawntapu National Park", "Devils @ Cradle"],
            "Outback": ["Queenstown", "Central Highlands"],
            "Winter Sport": ["Ben Lomond", "Mount Mawson", "Cradle Mountain (snow hiking, limited skiing)"],
            "Landmarks": ["Port Arthur", "Richmond Bridge", "Shot Tower", "Battery Point"],
            "Heritage/History": ["Cascades Female Factory", "Ross Village", "Coal Mines Historic Site", "Sarah Island"]
        },
        "South Australia": {
            "Family-Friendly": ["Adelaide Zoo", "Glenelg Foreshore Playground", "Carrick Hill Adventure Playground"],
            "Sport": ["Adelaide Oval", "Coopers Stadium", "The Bend Motorsport Park"],
            "Adventure": ["Kangaroo Island", "Flinders Ranges", "Naracoorte Caves", "River Murray Adventures", "Mount Gambier’s Sinkholes"],
            "Cultural/Arts": ["Adelaide Festival Centre", "Tandanya Institute", "South Australian Museum", "Art Gallery of South Australia"],

Explorate/templates/Adv_name.html
{% extends "base.html"%}
{% block title%}DataEntry{% endblock%}
{% block content%}
<div class="container_yaaa">
    <div class="device-frame">
      <form id="adventure-form" class="adventure-form">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="adventure-form">
            <div class="form-group" action="{{ url_for('main.questions') }}" method="POST">
                <label for="adventure_name" class="form-label">Adventure Name</label>
                <input type="text" id="adventure_name" class="form-input" value="Adventure 1" name="adventure_name">
            </div>
            
            <div class="form-group last-form-group">
                <label for="guests" class="form-label">Add Guest</label>
                <input type="text" id="guests" class="form-input" value="1 friend and 1 pet"readonly>
                
            </div>
        </div>
      </form>
    </div>
</div>
<div id="overlay" class="overlay"></div>

<div id="popup" class="popup hidden">
  <div class="text-center">
    <div class="mb-2">
      <div class="flex justify-between items-center bg-yellow-50 rounded mb-10 box">
        <div class="content-center">
          <p class="text-lg font-bold">Adults</p>
          <p class="text-sm">Ages 18 and above.</p>
        </div>
        <div class="flex items-center">
          <button class="decrement bg-green-600 text-white circle-btn" data-target="adults">-</button>
          <span id="adults" class="mx-3 text-lg">1</span>
          <button class="increment bg-green-600 text-white circle-btn" data-target="adults">+</button>
        </div>
      </div>

      <div class="flex justify-between items-center bg-yellow-50 rounded mb-10 box">
        <div class="content-center">
          <p class="text-lg font-bold">Children</p>
          <p class="text-sm">Ages below 18.</p>
        </div>
        <div class="flex items-center">
          <button class="decrement bg-green-600 text-white circle-btn" data-target="children">-</button>
          <span id="children" class="mx-3 text-lg">0</span>
          <button class="increment bg-green-600 text-white circle-btn" data-target="children">+</button>
        </div>
      </div>

      <div class="flex justify-between items-center bg-yellow-50 rounded mb-10 box">
        <div class="content-center">
          <p class="text-lg font-bold">Pets</p>
        </div>
        <div class="flex items-center">
          <button class="decrement bg-green-600 text-white circle-btn" data-target="pets">-</button>
          <span id="pets" class="mx-3 text-lg">0</span>
          <button class="increment bg-green-600 text-white circle-btn" data-target="pets">+</button>
        </div>
      </div>
    </div>

    <div class="bg-yellow-50 p-4 rounded mb-2 box">
      <div class="content-center">
        <p class="text-lg">Do you want to invite the group?</p>
        <div class="flex justify-around">
          <button id="yesButton" class="custom-blue text-white px-4 py-2 rounded">Yes</button>
          <button id="noButton" class="custom-blue text-white px-4 py-2 rounded">No</button>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container_button">
    <button id="nextButton" class="next-button" data-yes-url="{{ url_for('main.questions') }}" data-no-url="{{ url_for('main.questions') }}">Next</button>
</div>
{% endblock%}
{% block scripts %}
<script src="{{ url_for('static', filename='js/script_DataEnt.js') }}"></script>
{% endblock%}
 

Explorate/templates/Data_Ent_Q1.html
{% extends "base.html"%}
{% block title%}DataEntry{% endblock%}
{% block content%}
<nav>
    <div class="title-bar">
        <h1>{{adventure_name}}</h1>
    </div>
</nav>
<div class="container_yaaa">
    
    <div class="content-box">
        <div class="question">What climate do you like?</div>
        
        <div class="buttons-container">
            <button class="climate-button">Hot</button>
            <button class="climate-button">Cold</button>
            <button class="climate-button">Tropical</button>
        </div>
        
        <img src="https://i.postimg.cc/NjhF7F5L/Gemini-Generated-Image-gw1crzgw1crzgw1c-1.png" alt="Climate Options" class="climate-image">
    </div>
</div>
<div class="container">
    <div class="row align-items-center">
        <div class="col-3 ps-0 text-end">
            <button id="prev-button" class="next-button" style="width: 100%; display: none;">Previous</button>
        </div>
        <div class="col-6">
            <!-- Standard Bootstrap Progress Bar -->
            <div class="progress" style="height: 25px;">
                <div id="progress-bar" class="progress-bar progress-bar-striped progress-bar-animated bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">20%</div>
            </div>
        </div>
        <div class="col-3 ps-0 text-end">
            <button id="next-button" class="next-button" style="width: 100%;">Next</button>
        </div>
    </div>
</div>
<!-- This hidden input stores the adventure_id -->
<input type="hidden" id="adventure-id" value="{{ adventure_id }}">
<input type="hidden" id="user-id" value="{{ user_id }}">
{% endblock%}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="{{ url_for('static', filename='js/scriptQ.js') }}"></script>
{% endblock%}

Explorate/templates/Data_Entry.html
{% extends "base.html"%}
{% block title%}DataEntry{% endblock%}
{% block content%}
    
<!-- Flash messages block -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <ul id="flash-messages">
            {% for category, message in messages %}
                <li class="{{ category }} flash-message">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}
<!-- End of flash messages block -->

<section class="main-content">
    <h1>Your latest adventure awaits you.</h1>
    <button onclick="redirect()">Craft a new adventure</button>
</section>
{% endblock%}
{% block scripts %}
<script>
    function redirect() {
        window.location.href = "{{ url_for('main.adventure') }}"; // Replace with the file name of the target HTML
    }
</script>
{% endblock%}

Explorate/templates/base.html
<!DOCTYPE html>
<html lang="en" class="bg-white">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}Explorate{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
        rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles-share.css') }}"> 
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/consolidated.css') }}">
        <script src="{{ url_for('static', filename='js/name.js') }}"defer></script>
        <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    
    <!-- Bootstrap Icons -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
        
        {% block head %}{% endblock %}
    </head>

<body >
    <!-- Header Bar -->
    <div class="header">
        <button id="hamburger" class="hamburger">&#9776;</button>
        <img src="{{ url_for('static', filename='images/explorer.png') }}" alt="Logo" class="logo">
        {% if show_nav %}
        <nav class="navbar">
            <a href="{{ url_for('auth.login') }}">Login</a>
            <a href="{{ url_for('auth.sign_up') }}">Sign Up</a>
        </nav>
        {% endif %}
    </div>

    <!-- Sidebar -->
    <div id="sidebar">
        <a href="#"><img src="{{ url_for('static', filename='images/profile.png') }}" alt="Profile" class="sidebar-icon"> Profile</a>
        <a href="{{ url_for('main.FindAdv') }}"><img src="{{ url_for('static', filename='images/Itineray.png') }}" alt="Find_Itinerary" class="sidebar-icon"> Find Itinerary</a>
        <a href="{{ url_for('main.MyTrips') }}"><img src="{{ url_for('static', filename='images/trips.png') }}" alt="My_Trips" class="sidebar-icon"> My Trips</a>
        <a href="{{ url_for('main.user_analytics') }}"><img src="{{ url_for('static', filename='images/Insights.png') }}" alt="Insights" class="sidebar-icon"> Insights</a>
        
        <!-- Share Section with Dropdown -->
        <a href="javascript:void(0)" id="share-toggle" class="dropdown-toggle">
            <img src="{{ url_for('static', filename='images/IMG_9605.PNG') }}" alt="share" class="sidebar-icon"> Share
        </a>
        <div id="share-dropdown" class="dropdown-content hidden">
            <a href="{{ url_for('main.friend') }}">Share with someone</a>
            <a href="{{ url_for('main.friendView') }}">Shared to you</a>
        </div>
        <a href="{{ url_for('auth.logout') }}" id="logout">
            <img src="{{ url_for('static', filename='images/x-22.png') }}" alt="Log_out" class="sidebar-icon"> Log out
        </a>
    </div>
    

    {% block content %}

    <section class="main-content container my-5 p-4" style="max-width: 700px; color: #dfd8b6; text-shadow: 1px 1px 3px rgba(0,0,0,0.7);">
        <h1 class="mb-4 text-center" style="font-family: 'Itim'; font-size: 4.5rem; color: #dfd8b6;">Your ideal adventure awaits you!</h1>
        
        <p class="lead mb-4 text-center">
            Explore Australia like never before. Answer a quick questionnaire to generate a personalized itinerary,
            share your travel plans with friends, and analyze trip data to make smarter travel decisions.
        </p>
    
        <div class="text-center mb-4">
            <button onclick="redirect()" id="loginPage" class="btn btn-success btn-lg px-5">Get Started</button>
        </div>
    
        <!-- Steps with big icons -->
        <div class="d-flex justify-content-center gap-5 mt-5 icon-text-group">
            <div class="text-center">
                <i class="bi bi-question-circle"></i>
                <p class="text-bold">Get Recommendations</p>
            </div>
            <div>
                <i class="bi bi-share-fill icon-bold"></i>
                <p class="text-bold">Share Itinerary</p>
            </div>
            <div>
                <i class="bi bi-bar-chart-line-fill icon-bold"></i>
                <p class="text-bold">Analyze Trips</p>
            </div>
        </div>
        
    </section>
    
    
    {% endblock %}

    <!-- Bootstrap JS -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js">
    </script>
    <script>
        // Toggle Sidebar
        const sidebar = document.getElementById("sidebar");
        const main_part = document.getElementById("main_part");
        const toggleButton = document.getElementById("hamburger");

        toggleButton.addEventListener("click", () => {
            sidebar.classList.toggle("active");
            main_part.classList.toggle("active");
        });
        function redirect() {
        window.location.href = "{{ url_for('auth.login') }}"; // Replace with the file name of the target HTML
        }
        document.addEventListener("DOMContentLoaded", () => {
            const shareToggle = document.getElementById("share-toggle");
            const shareDropdown = document.getElementById("share-dropdown");
            const logout = document.getElementById("logout");

            shareToggle.addEventListener("click", () => {
                const isVisible = shareDropdown.classList.contains("visible");
                if (isVisible) {
                    shareDropdown.classList.remove("visible");
                } else {
                    shareDropdown.classList.add("visible");
                }
            });
        });
        
    </script>
    {% block scripts %}
    {% endblock %}
</body>
<div class="footer">
    &copy; 2025 Explorate
</div>
</html>

Explorate/templates/homepage.html
{% extends "base.html"%}
{% block title%}DataEntry{% endblock%}
{% block content%}
<header class="header">
    <nav class="navbar">
        <a href="auth.html?form=login">Login</a>
        <a href="auth.html?form=signup">Sign Up</a>
    </nav>
</header>
<section class="hero">
    <h1>Exciting adventures, just a click away!</h1>
</section>
{% endblock%}
{% block scripts %}
<script>
    function redirect() {
        window.location.href = "{{ url_for('main.adventure') }}"; // Replace with the file name of the target HTML
    }
</script>
{% endblock%}

Explorate/templates/index.html
{% extends "base.html"%}
{% block title%}Recommendations{% endblock%}
{% block content%}

<div class="recommendation-wrapper container mt-5">
    <h1 class="text-center mb-4">Your Personalized Adventure:</h1>
    <div id="results-container" class="recommendation-box"></div>
    <div class="text-center mt-4">
        <a href="{{ url_for('main.share_page') }}" id="share-button" class="btn btn-primary">Share</a>
    </div>
</div>
{% endblock%}

{% block scripts %}

<script src="{{ url_for('static', filename='js/ideal.js') }}"></script>

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recommendation.css') }}">
{% endblock %}

{% endblock%}

Explorate/templates/other-trips.html
{% extends "base.html"%}
{% block title%}Other Trips Page{% endblock%}
{% block content%}
<body>
        <div class = "section">
            <h2> See where others are traveling to!</h2>
            <img src= "{{ url_for('static', filename='images/auMap.png') }}" alt="Map of Australia">
            <!--Still need to do image mapping here-->
        </div>
    </body>
</html>
{% endblock %}

Explorate/templates/rate-page.html
{% extends "base.html"%}
{% block title%}Rate Page{% endblock%}
{% block content%}
    <div class = "section">
        <h2> Rate your itinerary!</h2>
        <h3>How would you rate your itinerary?</h3>
        <div class ="sub-section">
            <div class="rate-container">
                <div class = "rate" data-rating-id="1">
                    <h4>Location</h4>
                    <div class="star-container">
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                    </div>
                    <h3 class="output">Rating is: 0/5</h3>
                </div>
                <div class = "rate" data-rating-id="2">
                    <h4>Food</h4>
                    <div class="star-container">
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                    </div>
                    <h3 class="output">Rating is: 0/5</h3>
                </div>
                <div class = "rate" data-rating-id= "3">
                    <h4>Attractions</h4>
                    <div class="star-container">
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                    </div>
                    <h3 class="output">Rating is: 0/5</h3>
                </div>
                <div class = "rate" data-rating-id= "4">
                    <h4>Accommodation</h4>
                    <div class="star-container">
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                        <span class="star">★</span>
                    </div>
                    <h3 class="output">Rating is: 0/5</h3>
                </div>
                <input type="hidden" id="adventure-id" value="{{ adventure_id }}">
                <input type="hidden" id="user-id" value="{{ user_id }}">
                <input type="hidden" id="recommendation-id" value="{{ recommendation_id }}">

                <input type="hidden" id="csrf_token" name="csrf_token" value="{{ csrf_token() }}">
                <button class="btn" id="submit-rating-btn" data-share-url="{{ url_for('main.share_page') }}">Submit Ratings</button>
                <h3 id="overall-rating">Overall Rating: 0/5</h3>
            </div>
        </div>
    </div>
    <script src="/static/js/share_script.js"></script>

{% endblock %}